# Generated by Django 2.1.5 on 2019-02-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Category name"
                    ),
                ),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        )
    ]
